#!/usr/bin/env python3
"""Generate preview screenshots for README.

Generates a sample bilingual document, converts it to PDF,
extracts the first 10 pages as images, and outputs an HTML
gallery snippet ready to embed in README.md.
"""

import subprocess
import shutil
import tempfile
import sys
import os
from pathlib import Path
from main import main as main_cli


PREVIEW_DIR = Path(__file__).parent / "preview"
SAMPLE_ITEM_ID = "20264"
PDFS_DIR = Path(__file__).parent / "samples"


def check_dependencies() -> dict[str, str]:
    """Check that LibreOffice and pdftoppm are installed. Return paths."""
    deps = {}

    # Check LibreOffice
    for cmd in ["libreoffice", "soffice"]:
        if shutil.which(cmd):
            deps["libreoffice"] = cmd
            break
    if "libreoffice" not in deps:
        print("Error: LibreOffice not found. Install with: brew install libreoffice",
              file=sys.stderr)
        sys.exit(1)

    # Check pdftoppm (Poppler)
    if not shutil.which("pdftoppm"):
        print("Error: pdftoppm (Poppler) not found. Install with: brew install poppler",
              file=sys.stderr)
        sys.exit(1)
    deps["pdftoppm"] = "pdftoppm"

    return deps


def generate_sample_docx(item_id: str, pdf_en: Path, pdf_fr: Path, output_dir: Path) -> Path:
    """Generate a sample bilingual .docx using the formatter."""
    output_dir.mkdir(parents=True, exist_ok=True)
    output = output_dir / f"scc_{item_id}_preview.docx"

    print(f"Generating sample .docx from item {item_id}...")
    result = main_cli([
        item_id,
        "--lang-order", "en",
        "--output", str(output),
        "--pdf-en", str(pdf_en),
        "--pdf-fr", str(pdf_fr),
    ])

    if result != 0:
        print("Error: Failed to generate sample .docx", file=sys.stderr)
        sys.exit(1)

    if not output.exists():
        print(f"Error: Output file not created at {output}", file=sys.stderr)
        sys.exit(1)

    print(f"  → {output}")
    return output


def docx_to_pdf(docx_path: Path, pdf_path: Path, libreoffice_cmd: str) -> None:
    """Convert DOCX to PDF using LibreOffice headless."""
    print(f"Converting {docx_path.name} to PDF...")

    # Use temp dir for LibreOffice (it creates lock files)
    with tempfile.TemporaryDirectory() as tmpdir:
        cmd = [
            libreoffice_cmd,
            "--headless",
            "--convert-to", "pdf",
            "--outdir", tmpdir,
            str(docx_path),
        ]

        result = subprocess.run(cmd, capture_output=True, text=True)
        if result.returncode != 0:
            print(f"Error: LibreOffice conversion failed:\n{result.stderr}",
                  file=sys.stderr)
            sys.exit(1)

        # LibreOffice creates the PDF with the same basename
        temp_pdf = Path(tmpdir) / docx_path.with_suffix(".pdf").name
        if not temp_pdf.exists():
            print(f"Error: PDF not created by LibreOffice", file=sys.stderr)
            sys.exit(1)

        temp_pdf.rename(pdf_path)

    print(f"  → {pdf_path}")


def extract_pages_as_images(pdf_path: Path, output_dir: Path, num_pages: int = 10) -> list[Path]:
    """Extract first N pages of PDF as PNG images."""
    print(f"Extracting first {num_pages} pages as images...")

    output_dir.mkdir(parents=True, exist_ok=True)

    # pdftoppm: -f/-l for page range, -png for PNG output
    cmd = [
        "pdftoppm",
        "-f", "1",
        "-l", str(num_pages),
        "-png",
        "-r", "150",  # 150 DPI for readability
        str(pdf_path),
        str(output_dir / "page"),  # Output prefix
    ]

    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0:
        print(f"Error: pdftoppm failed:\n{result.stderr}", file=sys.stderr)
        sys.exit(1)

    # Collect generated images (pdftoppm names them page-1.png, page-2.png, etc.)
    images = sorted(output_dir.glob("page-*.png"))
    if not images:
        print("Error: No images generated by pdftoppm", file=sys.stderr)
        sys.exit(1)

    print(f"  → {len(images)} pages extracted")
    return images


def generate_html_gallery(images: list[Path], sample_id: str) -> str:
    """Generate an HTML/Markdown snippet for a carousel gallery."""
    html = f"""<!-- Generated preview of SCC {sample_id} -->
<div id="scc-preview-gallery">
  <p><em>Preview of the bilingual document (first {len(images)} pages, French left / English right):</em></p>
  <div style="display: flex; flex-direction: column; gap: 2rem; max-width: 900px; margin: 2rem 0;">
"""

    for i, img in enumerate(images, 1):
        rel_path = img.relative_to(Path(__file__).parent)
        # Create alt text describing the page
        alt_text = f"Page {i} of SCC {sample_id} bilingual document"
        html += f"""    <figure>
      <img src="{rel_path}" alt="{alt_text}" style="width: 100%; border: 1px solid #ddd; border-radius: 4px;">
      <figcaption style="text-align: center; font-size: 0.9em; color: #666; margin-top: 0.5rem;">Page {i}</figcaption>
    </figure>
"""

    html += """  </div>
</div>
"""
    return html


def main_generate_preview():
    """Main entry point: generate preview and output gallery HTML."""
    # Check dependencies
    deps = check_dependencies()
    libreoffice_cmd = deps["libreoffice"]

    # Verify sample PDFs exist
    pdf_en = PDFS_DIR / f"{SAMPLE_ITEM_ID}_en.pdf"
    pdf_fr = PDFS_DIR / f"{SAMPLE_ITEM_ID}_fr.pdf"

    if not pdf_en.exists() or not pdf_fr.exists():
        print(f"Error: Sample PDFs not found in {PDFS_DIR}", file=sys.stderr)
        print(f"  Expected: {pdf_en.name}, {pdf_fr.name}", file=sys.stderr)
        sys.exit(1)

    # Create preview directory
    PREVIEW_DIR.mkdir(exist_ok=True)

    try:
        # Step 1: Generate sample DOCX
        docx_path = generate_sample_docx(SAMPLE_ITEM_ID, pdf_en, pdf_fr, PREVIEW_DIR)

        # Step 2: Convert to PDF
        pdf_path = PREVIEW_DIR / f"scc_{SAMPLE_ITEM_ID}_preview.pdf"
        docx_to_pdf(docx_path, pdf_path, libreoffice_cmd)

        # Step 3: Extract first 10 pages as PNG
        images = extract_pages_as_images(pdf_path, PREVIEW_DIR / "pages")

        # Step 4: Generate HTML gallery
        gallery_html = generate_html_gallery(images, SAMPLE_ITEM_ID)

        # Step 5: Write gallery snippet to file
        gallery_file = PREVIEW_DIR / "gallery.html"
        gallery_file.write_text(gallery_html)

        print()
        print("✓ Preview generated successfully!")
        print(f"  Images: {PREVIEW_DIR / 'pages'}/")
        print(f"  Gallery snippet: {gallery_file}")
        print()
        print("To add to README.md, copy the following (or include the file):")
        print("=" * 60)
        print(gallery_html)
        print("=" * 60)

    finally:
        # Clean up DOCX (no need to keep it, PDF + images are the goal)
        if docx_path.exists():
            docx_path.unlink()


if __name__ == "__main__":
    main_generate_preview()
